steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
    env:
      - spring_profiles_active=$_SPRING_PROFILES_ACTIVE
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-f", "src/main/docker/Dockerfile", "-t", "gcr.io/$PROJECT_ID/api-dna:latest", "--build-arg=JAR_FILE=target/api-dna-0.0.1-SNAPSHOT.jar", "."]
images: ["gcr.io/$PROJECT_ID/api-dna:latest"]
