CREATE TABLE IF NOT EXISTS dna (
    id UUID PRIMARY KEY NOT NULL,
    dna VARCHAR ARRAY NOT NULL,
    hash CHAR(64) NOT NULL,
    mutant BOOLEAN NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_dna_hash ON dna (hash);
