version: '3.9'
services:
  web:
    image: api-dna:latest
    hostname: api-dna
    networks:
#      - schambeck-overlay
      - schambeck-bridge
      - backend
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dna
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - CUSTOM_API_NOTIFICATION_SERVICE_ID=api-notification
      - DISCOVERY_URI=http://srv-discovery:8761/eureka
      - AUTH_URI=http://srv-authorization-kc:9000
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_VIRTUAL_HOST=
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 384M
        reservations:
          memory: 256M
    ports:
      - "8080:8080"
  db:
    image: 'postgres:12.9-alpine'
    networks:
      - backend
    environment:
      - POSTGRES_DB=dna
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  haproxy:
    image: haproxytech/haproxy-alpine:latest
    networks:
#      - schambeck-overlay
      - schambeck-bridge
      - backend
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "4000:80"
      - "8404:8404"
    deploy:
      replicas: 0
networks:
  schambeck-bridge:
    external: true
  #  schambeck-overlay:
  #    external: true
  backend: {}
