version: '3.9'
services:
  web:
    image: api-dna:latest
    networks:
      - schambeck-net
    environment:
      - SERVER_PORT=80
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-dna:5432/dna
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - CUSTOM_CORS_ALLOWED_ORIGINS=http://localhost:4200
      - CUSTOM_API_NOTIFICATION_SERVICE_ID=http://api-notification
      - DISCOVERY_URI=http://srv-discovery:8761/eureka
      - AUTH_URI=http://srv-keycloak.localhost/realms/schambeck
      - TRACING_URI=http://srv-tracing:9411
      - SPRING_RABBITMQ_HOST=srv-rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_VIRTUAL_HOST=
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 384M
        reservations:
          memory: 256M
      labels:
        - traefik.enable=true
        - traefik.http.services.api-dna.loadbalancer.server.port=80
  db:
    image: 'postgres:12.9-alpine'
    networks:
      schambeck-net:
        aliases:
          - db-dna
    environment:
      - POSTGRES_DB=dna
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
networks:
  schambeck-net:
    external: true
