version: '3.9'
services:
  discovery:
    image: mschambeck/srv-discovery:latest
    networks:
      schambeck-net:
        aliases:
          - srv-discovery
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    ports:
      - target: 8761
        published: 8761
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      schambeck-net:
        aliases:
          - srv-rabbitmq
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    ports:
      - target: 5672
        published: 5672
      - target: 15672
        published: 15672
  config:
    image: mschambeck/srv-config:latest
    networks:
      schambeck-net:
        aliases:
          - srv-config
    environment:
      - DISCOVERY_URI=http://srv-discovery:8761/eureka
      - SPRING_RABBITMQ_HOST=srv-rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_VIRTUAL_HOST=
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
  tracing:
    image: openzipkin/zipkin
    networks:
      schambeck-net:
        aliases:
          - srv-tracing
    ports:
      - target: 9411
        published: 9411
    deploy:
      resources:
        limits:
          memory: 384M
        reservations:
          memory: 256M
  proxy:
    image: traefik:latest
    networks:
      - schambeck-net
    command:
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.defaultRule=Host(`{{ index .Labels "com.docker.stack.namespace" }}.localhost`)
      - --api.dashboard=true
      - --api.insecure=true
    ports:
      - target: 80
        published: 80
      - target: 8080
        published: 8080
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  keycloak:
    image: srv-keycloak:latest
    command:
      - start-dev
      - --import-realm
    networks:
      schambeck-net:
        aliases:
          - srv-keycloak.localhost
    environment:
      - KC_HTTP_PORT=80
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - REALM_NAME=schambeck
    deploy:
      resources:
        limits:
          memory: 640M
        reservations:
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.http.routers.srv-keycloak.rule=Host(`srv-keycloak.localhost`)
        - traefik.http.services.srv-keycloak.loadbalancer.server.port=80
  ldap:
    image: bitnami/openldap
    networks:
      schambeck-net:
        aliases:
          - srv-ldap
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ROOT=dc=schambeck,dc=com
      - LDAP_BIND_DN=cn=admin,dc=schambeck,dc=com
      - LDAP_BIND_PASSWORD=admin
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
    volumes:
      - 'openldap_data:/bitnami/openldap'
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M
volumes:
  openldap_data:
    driver: local
networks:
  schambeck-net:
    name: schambeck-net
    driver: overlay
